theme: jekyll-theme-minimal
title: Harry Kelly
pronouns: he/they
description: Fourth year computer science student at the University of York
show_downloads: false
logo: assets/profile.jpg

github:
  is_project_page: false