theme: jekyll-theme-minimal
title: Harry Kelly
pronouns: he/they
description: Fourth year computer science student at the University of York.  Available for work starting June 2023
show_downloads: false
logo: assets/profile.jpg

cv:
  url: /assets/Harry Kelly CV.pdf
  text: Download CV

github:
  is_project_page: false
