theme: jekyll-theme-minimal
title: Harry Kelly
pronouns: he/they
description: MEng Computer Science Graduand, University of York
show_downloads: false
logo: assets/profile.jpg

cv:
  show: true
  url: https://www.harrykelly.me/assets/HarryKellyCV.pdf
  text: View CV

github:
  is_project_page: false
